### ISSUE TITLE
Add ranged enemy

### ISSUE THREAD

**Issue by ApGoldberg** [ljhs-games/week-75#1]

**Comment by ApGoldberg** [comment]
Node should be a RigidBody2D that orbits the player but does not advance toward it and spawns arrows.

**Comment by creikey** [comment]
As discussed in #8 , when spawning arrow, it should add the arrow as a child of  its parent. This means the various projectiles should be contained in a Node2D, something like `Enemies` for easier debugging

**Comment by creikey** [comment]
Accidentally merged in [this commit](https://github.com/ljhs-games/week-75/commit/2af7ecdf03164f1a90230c3e4b07c445877f5ce8)
