### ISSUE TITLE
Add puddles

### ISSUE THREAD

**Issue by ApGoldberg** [ljhs-games/week-75#3]
Needs to light up when hit and do damage to enemies that are in it

**Comment by ApGoldberg** [comment]
Node should be an Area2D that turns yellow if entered by the lightning node or kills an enemy if entered by both a lightning node and an enemy.

**Comment by creikey** [comment]
Should keep track of a list of rigidbodies in side of it in an array, then goes through that array and if the group is `enemy` or `player` then it should call `shocking(true)` on it, wait the puddle shock length of time, then call `shocking(false)`

**Comment by creikey** [comment]
Implementation changed to just using built in `Area2D` functions to get bodies inside the puddle rather than keeping track of it manually
