### ISSUE TITLE
Add gravitational bullet

### ISSUE THREAD

**Issue by ApGoldberg** [ljhs-games/week-75#5]

**Comment by ApGoldberg** [comment]
Node should be an Area2D that has it's own gravity assigned to it. It should pull all enemies and the player towards it. There should be cooldown of 5 seconds before it can be used again.

**Comment by creikey** [comment]
Cooldown will be managed by the player. 
- gravity effect should last for 3 seconds on impact wherever the mouse is
- gravity effect should be disabled while traveling
- movement should be managed by a tween that travels for 0.5 seconds
- have a method called `launch(target_position)` to set the target position for it to go to and to launch towards, then start going towards point
