### ISSUE TITLE
Add lightning bullet

### ISSUE THREAD

**Issue by ApGoldberg** [ljhs-games/week-75#7]

**Comment by ApGoldberg** [comment]
Fired by the player. Node should be an Area2D that disappears once it enters the puddle node.

**Comment by creikey** [comment]
It should also call a method called `shock()` on the puddle when it detects a puddle in the area

**Comment by creikey** [comment]
After shocking the lightning bolt should also `queue_free()`

**Comment by creikey** [comment]
The lightning bolt should be added to the parent of the player node
